"""add date format

Revision ID: 1a34685c3b0f
Revises: bd7c76480677
Create Date: 2025-11-08 09:56:01.559981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a34685c3b0f'
down_revision: Union[str, Sequence[str], None] = 'bd7c76480677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction_notices', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('construction_notices', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('construction_notices', 'date_range')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction_notices', sa.Column('date_range', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('construction_notices', 'end_date')
    op.drop_column('construction_notices', 'start_date')
    # ### end Alembic commands ###
